---
global_config:
  environment_name: sample
  cloud_platform: ibm-cloud
  ibm_cloud_region: eu-de
  env_id: cp4d-csm-dach #has to be all lowercase and ruther short because VPCs get the same name
  confirm_destroy: False


openshift:
- name: "{{ env_id }}"
  cluster_name: "{{ env_id }}"
  domain_name: cpd-zen-46.cp4d-csm-dach-8cd80e6462885b8080a9985873dae1d8-0000.eu-de.containers.appdomain.cloud
  ocp_version: 4.13.0  # it is necessary to specify minor version because cloudpak deployer turns 4.10 into 4.1 otherwise :-(
  openshift_storage:
  - storage_name: ocs-storage
    storage_type: ocs
    ocs_storage_label: ocs
    ocs_storage_size_gb: 500
    ocs_version: 4.11.0
